name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     example: [path/to/test/file.c, examples/file.ino, path/to/test/directory]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout upstream firmware
      uses: actions/checkout@v2
      with:
        repository: th3dstudio/UnifiedFirmware
        ref: "2.31"
        path: upstream

    # with:
      #   repository: talltechdude/ender3-firmware
    # - run: |
    #     pwd
    #     ls -al
    #     ls -al upstream/
    - name: Prepare custom config
      run: |
        # pwd
        # ls -al ../
        # ls -al
        cp "upstream/Board Configuration Files/TH3D_EZBoardLite/Firmware/platformio.ini" upstream/Firmware/
        cat Configuration_pre.h "upstream/Board Configuration Files/TH3D_EZBoardLite/Firmware/Marlin/Configuration.h" Configuration_post.h > upstream/Firmware/Marlin/Configuration.h
        # ls -al upstream/Firmware
        # ls -al upstream/Firmware/Marlin/
        # cat upstream/Firmware/Marlin/Configuration.h

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: pio run
      working-directory: ./upstream/Firmware
    - name: Export artifact
      run: |
        ls -al .pio/build/
        ls -al .pio/build/TH3D_EZBoardLite
      working-directory: ./upstream/Firmware