name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     example: [path/to/test/file.c, examples/file.ino, path/to/test/directory]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout upstream firmware
      uses: actions/checkout@v2
      with:
        repository: th3dstudio/UnifiedFirmware
        ref: "2.31"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - run: |
        pwd
        ls -al

    # - name: Run PlatformIO
    #   run: pio ci --board=<ID_1> --board=<ID_2> --board=<ID_N>
    #   env:
    #     PLATFORMIO_CI_SRC: ${{ matrix.example }}